<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermohonanInformasiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('permohonan_informasi')->insert([
            [
                'nama' => 'Budi Santoso',
                'nik' => '1234567890123456',
                'alamat' => 'Jl. Melati No. 10, Jakarta',
                'email' => 'budi@gmail.com',
                'file_ktp' => 'ktp_budi.jpg',
                'pekerjaan' => 'Pegawai Swasta',
                'no_telepon' => '081234567890',
                'informasi_yang_dibutuhkan' => 'Laporan Keuangan Q2 2024',
                'alasan_penggunaan_informasi' => 'Penyusunan laporan tahunan',
                'memperoleh_informasi_id' => 1,
                'mendapatkan_salinan_informasi_id' => 4,
                'status_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Siti Aminah',
                'nik' => '6543210987654321',
                'alamat' => 'Jl. Mawar No. 23, Bandung',
                'email' => 'siti@gmail.com',
                'file_ktp' => 'ktp_siti.jpg',
                'pekerjaan' => 'Wiraswasta',
                'no_telepon' => '081298765432',
                'informasi_yang_dibutuhkan' => 'Data Pelanggan Terkini',
                'alasan_penggunaan_informasi' => 'Analisis tren penjualan',
                'memperoleh_informasi_id' => 2,
                'mendapatkan_salinan_informasi_id' => 5,
                'status_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Andi Wijaya',
                'nik' => '1098765432109876',
                'alamat' => 'Jl. Anggrek No. 5, Surabaya',
                'email' => 'andi@gmail.com',
                'file_ktp' => 'ktp_andi.jpg',
                'pekerjaan' => 'PNS',
                'no_telepon' => '081234567891',
                'informasi_yang_dibutuhkan' => 'Data Inventaris Gudang',
                'alasan_penggunaan_informasi' => 'Optimalisasi stok barang',
                'memperoleh_informasi_id' => 3,
                'mendapatkan_salinan_informasi_id' => 4,
                'status_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Rina Kurniawati',
                'nik' => '1234987654321098',
                'alamat' => 'Jl. Kenanga No. 12, Medan',
                'email' => 'rini@gmail.com',
                'file_ktp' => 'ktp_rina.jpg',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'no_telepon' => '081345678912',
                'informasi_yang_dibutuhkan' => 'Hasil Survei Kepuasan Pelanggan',
                'alasan_penggunaan_informasi' => 'Meningkatkan kualitas layanan',
                'memperoleh_informasi_id' => 1,
                'mendapatkan_salinan_informasi_id' => 5,
                'status_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Ahmad Manafi',
                'nik' => '9876543210987654',
                'alamat' => 'Jl. Dahlia No. 7, Makassar',
                'email' => 'ahmad@gmail.com',
                'file_ktp' => 'ktp_ahmad.jpg',
                'pekerjaan' => 'Pengusaha',
                'no_telepon' => '081567890123',
                'informasi_yang_dibutuhkan' => 'Data Proyek Berjalan',
                'alasan_penggunaan_informasi' => 'Monitoring dan evaluasi proyek',
                'memperoleh_informasi_id' => 2,
                'mendapatkan_salinan_informasi_id' => 4,
                'status_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dewi Lestari',
                'nik' => '3456789012345678',
                'alamat' => 'Jl. Cendana No. 15, Yogyakarta',
                'email' => 'dewi@gmail.com',
                'file_ktp' => 'ktp_dewi.jpg',
                'pekerjaan' => 'Dosen',
                'no_telepon' => '081678901234',
                'informasi_yang_dibutuhkan' => 'Data Penelitian Terbaru',
                'alasan_penggunaan_informasi' => 'Pengembangan riset akademik',
                'memperoleh_informasi_id' => 3,
                'mendapatkan_salinan_informasi_id' => 5,
                'status_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Rudi Hartono',
                'nik' => '5678901234567890',
                'alamat' => 'Jl. Flamboyan No. 8, Semarang',
                'email' => 'rudi@gmail.com',
                'file_ktp' => 'ktp_rudi.jpg',
                'pekerjaan' => 'Wartawan',
                'no_telepon' => '081789012345',
                'informasi_yang_dibutuhkan' => 'Laporan Kinerja Pemerintah',
                'alasan_penggunaan_informasi' => 'Penyusunan artikel berita',
                'memperoleh_informasi_id' => 1,
                'mendapatkan_salinan_informasi_id' => 4,
                'status_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Maya Sari',
                'nik' => '7890123456789012',
                'alamat' => 'Jl. Bougenville No. 20, Denpasar',
                'email' => 'maya@gmail.com',
                'file_ktp' => 'ktp_maya.jpg',
                'pekerjaan' => 'Mahasiswa',
                'no_telepon' => '081890123456',
                'informasi_yang_dibutuhkan' => 'Data Statistik Penduduk',
                'alasan_penggunaan_informasi' => 'Penyusunan skripsi',
                'memperoleh_informasi_id' => 2,
                'mendapatkan_salinan_informasi_id' => 5,
                'status_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Hendra Gunawan',
                'nik' => '9012345678901234',
                'alamat' => 'Jl. Teratai No. 3, Palembang',
                'email' => 'hendra@gmail.com',
                'file_ktp' => 'ktp_hendra.jpg',
                'pekerjaan' => 'Konsultan',
                'no_telepon' => '081901234567',
                'informasi_yang_dibutuhkan' => 'Rencana Tata Ruang Kota',
                'alasan_penggunaan_informasi' => 'Analisis pengembangan wilayah',
                'memperoleh_informasi_id' => 3,
                'mendapatkan_salinan_informasi_id' => 4,
                'status_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}